# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DLFS

import flatbuffers

class BoundingBox(object):
    __slots__ = ['_tab']

    # BoundingBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingBox
    def Y1(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BoundingBox
    def X1(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # BoundingBox
    def Y2(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # BoundingBox
    def X2(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateBoundingBox(builder, y1, x1, y2, x2):
    builder.Prep(4, 16)
    builder.PrependFloat32(x2)
    builder.PrependFloat32(y2)
    builder.PrependFloat32(x1)
    builder.PrependFloat32(y1)
    return builder.Offset()
